name: Deploy

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-3-144-245-2.us-east-2.compute.amazonaws.com"
          username: "ubuntu"
          key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA2BNFttO/TDiIlPUyKGfaCBALgl4E9ia+7conD7jwnsUvcFlUgWcL
NefQikC2rzhCF+y7b2O9aTIswRlJmqb6HFaBXqFLjNm6LL2n7aOD7VGrHndK+udFRJI+KS
oPLMIqn8bltWijRXbS78hvmx2sDkyxth3j8P2D4Qg8WQP8PxXzaYVK/Cd5UfEsPQaBCRJW
pQd2B5nwp9+NrwoxciK4FHBTbrPKU8AAubt59BDUpBlBR2sw+qPif/zd3+K5iJfMTiGpWZ
pY3ckh0EWPHDmR6OnXd9IXGHeHov/fYE+785FsRBDCl22p4rU8u1XeVIQylAJo686+QQdR
fFNbb0KL7iMUM5vuTCEY9idp2EnltLkNfLNQuen6saZ29FNWa2S8CesMMvy3UNIYxvjZQD
F8ysNtekj+4eCCfS4LlH4gG4py4a28epLMMNcqpx1jJnL0E2xLEg5mQSqykPhNM341xrLi
HUr71+/69zibude2gmpMSIkOTxg8KZ7vqEakLwtNAAAFkDdZ1+M3WdfjAAAAB3NzaC1yc2
EAAAGBANgTRbbTv0w4iJT1Mihn2ggQC4JeBPYmvu3KJw+48J7FL3BZVIFnCzXn0IpAtq84
Qhfsu29jvWkyLMEZSZqm+hxWgV6hS4zZuiy9p+2jg+1Rqx53SvrnRUSSPikqDyzCKp/G5b
Voo0V20u/Ib5sdrA5MsbYd4/D9g+EIPFkD/D8V82mFSvwneVHxLD0GgQkSVqUHdgeZ8Kff
ja8KMXIiuBRwU26zylPAALm7efQQ1KQZQUdrMPqj4n/83d/iuYiXzE4hqVmaWN3JIdBFjx
w5kejp13fSFxh3h6L/32BPu/ORbEQQwpdtqeK1PLtV3lSEMpQCaOvOvkEHUXxTW29Ci+4j
FDOb7kwhGPYnadhJ5bS5DXyzULnp+rGmdvRTVmtkvAnrDDL8t1DSGMb42UAxfMrDbXpI/u
Hggn0uC5R+IBuKcuGtvHqSzDDXKqcdYyZy9BNsSxIOZkEqspD4TTN+Ncay4h1K+9fv+vc4
m7nXtoJqTEiJDk8YPCme76hGpC8LTQAAAAMBAAEAAAGAeqlWJhfGvSpKvuUC+FUcPP9+yR
8+ic4tDSh5TD+cuUUPTSQpCNzKTGuwwwtBqe6x9or5TJ6+Y/2L0oLceeLYkUW6Y1IFZYwk
WEnCDvGIbyyxi7YE5rJrbCXpC81ImAwRzmpG9NjV9xUhYeXTFaeeiO+Y4t3NDH2eZB0cxR
uyEs4PRJPaoZJ3GMFkb7BFiDTU4xJ9Oot1RpduAzQyJaz3+wJZGrsN3MVepBF9hcQYMp/z
ouuC/oYSir2t5u76jEQ/N1V6bcW5hqEcppvjU9U2m9Zjvpkh0RwJXSWkirXfZ354BrKTiW
6h/m6X9kENFpfAdDIBZ5EvYtF+qVnTbkqEPeHc+99NPazyC4ll6tcURwo9E6PBDnpmOCLN
/O0qujl9dr9zNcbDrT7+ShXMiO9iHxuF0Xf1YQ+2h5h7rcDgM6X7SFFNpqsY3AB2/MQzrW
5CgHYXlPd+Jvp3CmuOfJdgIWtMRz0smftgVTJFJ2bqKnSJuEf2VlucFxPiJIxnS1MBAAAA
wQDYZoTNGO0M4u/b5n5PlACNq2tE18sHMA9i2ZJxbtBU08Gfd8z/UHSeO4WquHjXIGz757
oU/L8xaa3YpEY9rJ99Ry+8h7et4rXjAsc0CNm6OY5iVeO8IF/31GpNQ4qxh4C4tjXxjwPH
IbOTpmY+qZjx/4bd2qJlzEiZyM8vljanfRTNCpeHz+OO+YkX7peg2N5ZimUiEio4gxpRHS
arBwwC5A9fDNzjtR0TxIZiCX7fn2wPwWiqqtQ+bq7nA3JLNP0AAADBAPyU0+KzI9Hl3M4i
O5s9T56qgzONN+9ZvWcOjFjxya3QkY7WvjqsufqAfG5uqWIc4tpKsor3Pt1pe36V3qCtJq
IBA+AiWyg+FH8KD6MxQV1sAdwzBO4WlYEDtc2g6H6zbjMGckcK95xV6Nfxq5eGq0tDdkzF
1QKMhknnx+dfu+JMedILHszaAztF9hb9FfmiGYLzoB2Esf823F9X9S2uvID5r3/shQxcDo
jhNiwc2ggRsE/Ekf4qVqJr+2tuTKDnkQAAAMEA2v/0S+HYSdNywUm1b5Yn6jWkxHEgmNnJ
82V9vlRTczXAcStp+wdf8xn7QDUouo0+9rijINSyh08beDDVvGeF/jnTIOJLrm1axukMAq
NXUINESSl7GC5NTy4mBzcm8c9//IMLAk7FC2owljw5+IPEtbXu/xE48s63loFH2DCZUErH
ZGCZmvICruBtFrI68Wfnz+jwBOvHJkllCXN5Pji/bOTWxwe8vUP6aMN+lsHeekzM4EmEqt
0zQ8P/KWVLCKH9AAAAF3VidW50dUBpcC0xNzItMzEtNDEtMjI2AQID
-----END OPENSSH PRIVATE KEY-----"
          script: sh deploy.sh