name: Deploy

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 3.144.245.2
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          script: sh deploy.sh