name: Deploy

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-3-144-245-2.us-east-2.compute.amazonaws.com"
          username: "ubuntu"
          key: "-----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQEAmJLcYcGwRmETq1rz7x4O29rNyz019y11dmo4cmplWlLTF0+u
              Cb1yyawHW5oYZOD0F808ff2npvmfGg5Azkeimr3iHc/WuAFiY9ij52fd4x0EISeM
              8wft2qgZ41R/0aCnJ5O36/suqtIRNkxcS2wF2ouSwhp4JxQrabDEbL+0vFo4XovV
              tWLbSoww3frev4DxKBSg+Ch6P5jzY90Hybe+8mwDyVio+L7+jidnuAri/gCQrkpW
              Q7dG5HPndJKWB0O9I5DlOs5W8R/xVdkilG3+9/+iMoA4AoDkYktISTqlo8mZ5Ewm
              G6sTbjRnaHCE8L0LRIj+kc4bNW35h7/ecoZ9yQIDAQABAoIBAF9xd4V7qa7NKYXH
              FtOdhQQJgzVBbFHc0R8rYXZJkm+HYl+xy5hyN61q/QtTgTER/AArtkzGcaslel7N
              TcL80v5kDGBD1Pk0fH0jV5z5v7dEPoITALxDWIqxH8iy4mabThWW9bYcYlwfnv7N
              k+rmf17wcvUTo9gmaOXr22SAJCqydWAFg6lOITGzZTMeqM53tsp79xiIovYiVbK3
              ynWz5G3wsG/TpMvq2o5VQUM4pjkR7e4Bvpm364Ofr4utdVJaW9ob8MN/JMLfivOl
              FCqDfD+y/q5186dcjJAcOPgUtVWnbg9Wdz30AqPrWXyS4jvOKYkQVZvAXMthwKJQ
              u6STDlECgYEA8UDRQhwehrchW4hMBKhhdh7Y+5F4J6ncRgPMp53CJUUMJWeSsN7Q
              9UhYt5rwkzx7PHhKzsR9vLPUaBBqzoB+Z9tRjQxaTM8wixo5+ejo9r9JuvGjsusY
              5VLxTXvj/sezC7I/CZGADOt8zPKWT/r5YjWb6oZZIu1Fxg1QDbeW0e0CgYEAoeZd
              9Ll+z9phetthwm+W/WLFuvDoyYj/JkWfTtWUNmMA4IulwcDMzpl6CrwvQ8y8F4wg
              7sz+uQTse7efq8175FZqzLxmkAlXzMU1sVyP2Uzdpw1hAxHFxktsbmiE4ed0TcYe
              1FCZiM5MipGmYtoMotZnKFagbvUfU+ehLWHRj80CgYEA3hxvy+65iAu4MV41pqAj
              Qq251TqjpdizzN4YoEUVBl0ghptpqV8qgHh//WIvlU68ovqY3O54WLAzoS9kNgSE
              3DdGSJaT2F10cszNjbEKMooAZpWrwcDCpfcL4+tpCBtxUxZjBPspKjvwJXw+ORp2
              WR3EE1JnZEmQ0HtXNZnNyC0CgYAG1oQBYhRJEyAq4DkwzSXDbfiL/MDYQkEEjMw9
              uCeaZHQVB9Dobgw4baMJ8QjOBEetdu2tKFtZ1StnzkmgJ/2jl0LLgumSC9L5gxrR
              cudgdi6mb5o5VvbTeTwLLb7vC6eN4WBL91uEu7Hf6GbupecCuauBuKbuCMxZ7t6P
              3CHNwQKBgGPy51UiXsA2c7en4s18VLmifjO3FXpeaf/gWjG2Fy+7FjEubYrlrEhy
              +k+0lLtdngILMVofizBF4sOSzbtPsI0n86J480m47NJBd7+O1oG4+u4Q3uA01I57
              sy4qcsTRfsfzSHK4wFJyq3rZ6/FG8v6kiN76KwoT1B205zHuXRbg
              -----END RSA PRIVATE KEY-----"
          script: sh deploy.sh