name: Deploy

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-3-144-245-2.us-east-2.compute.amazonaws.com"
          username: "ubuntu"
          key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAp3xqcAu6bAEXTjAxYQA/udBqRuL6rOgOnWBbr0p/nDdNOaqK4dSx
qJ+yB0m7eo6JlH8Cbhe5UAVP8//p3QbxyJicvSD1jtmXzQRwj2+GSrc5ZRK9kYjjuTNbHw
hpV/BGWYgStkih1qEPMM/Weo8zTU/qJ/QUA+bep+DPnhgaIc26JPymYR2RgLvNndL4/WVT
GJHIzRJSA9dhsL3lynGcwdkY24/bCe7z9M+T+ygIzbaq1aURuMqgAijfYh/NDxGZ+Hfdpc
I8xbW37rLIiqvC/KQDKCiRrzgJ8GSSCUJDhjcNAlyUpxRqVRFTQlKL+HfntCfC7Do5Lyfs
4sTjHS2J0S14ryObpr8pdjA4/R1UhdsFkXqvrrxJDrDNv9XVgrsBBEECkhSZ1qH4D/Um9O
KZIAyW/MXScoMbQy12DAOZdhg6XVb3xLwt+gDsvMVHpSUb33EC+C8xSDGhd+mM2/qzoRG5
9Lo9cj6Yt+e6u+0YfkGuIx8xKbzkyPAnbGOQL8yDAAAFkLAIqcewCKnHAAAAB3NzaC1yc2
EAAAGBAKd8anALumwBF04wMWEAP7nQakbi+qzoDp1gW69Kf5w3TTmqiuHUsaifsgdJu3qO
iZR/Am4XuVAFT/P/6d0G8ciYnL0g9Y7Zl80EcI9vhkq3OWUSvZGI47kzWx8IaVfwRlmIEr
ZIodahDzDP1nqPM01P6if0FAPm3qfgz54YGiHNuiT8pmEdkYC7zZ3S+P1lUxiRyM0SUgPX
YbC95cpxnMHZGNuP2wnu8/TPk/soCM22qtWlEbjKoAIo32IfzQ8Rmfh33aXCPMW1t+6yyI
qrwvykAygoka84CfBkkglCQ4Y3DQJclKcUalURU0JSi/h357Qnwuw6OS8n7OLE4x0tidEt
eK8jm6a/KXYwOP0dVIXbBZF6r668SQ6wzb/V1YK7AQRBApIUmdah+A/1JvTimSAMlvzF0n
KDG0MtdgwDmXYYOl1W98S8LfoA7LzFR6UlG99xAvgvMUgxoXfpjNv6s6ERufS6PXI+mLfn
urvtGH5BriMfMSm85MjwJ2xjkC/MgwAAAAMBAAEAAAGAFHsEUPs+KqLfhLIj96aeJEy2Ek
EDQk2GK/xyebb0b9fbW6fdH8xwhRwyGu4LPOtdK4l0dJ32DTD5G+85W8vTmSIAWKhFHtjA
1VMrqH6Mv2o0XIW0JK3GmwkKpXrT1usMzznyf9PV5nb/coqXwZjtPxD8ozIXmHqM056MBN
sRpvyPPKKgfdOtzT4p4JjB1cqkJKb/FQSeftXBnmk6Rk0qTBIOFhs7P7W2o0MW52l32h/y
N/nddulgM6Nn3Ynh+2u9Y5szybUcqVrup/zq9asmcOh3N/mUFI5RA+yC0nokm3MGvJ1Ji5
fGm1aBvgPFqF9Rh3oOFrZofHa/SMsKIKR73a3HESjTzAfE9q4gWRyU6zZ7ITo6sgovjF5W
9mH54vyH3wS3KiuEOAhcB+PE1OpV6ve8CqCvT00envWCDablkXk+JEN/tgBlzEPVYEXa8H
CQvHAmwV+gG/46pynJwJ9Zou1SCbh2rZ0lgxCUVK8Lj12N+nac50J92BrVnNAM9auRAAAA
wQCGCDpo004t6OT7GntnJ0MUe/1aAsSRxPSsWZTowwmHqZVTmxMPpd9r/l37Evxvrf8/Lm
fctw1AdFFs1Er7+OR1y8sz2P8vrWLRtAtkzcPYn5W0pqmofBHRMHKUwBDQqzApANoKbX/S
mc5ol7wLitxDzDbCZgHrO1hsKE4zmgJfcz0xytuxbMQTC8mVPqKbTTsiIOGg8pujSw6U1j
otQOR6wW0MGNnXNv2n1MdNHaaNe5Ns1+bd6HjCfroHBCUN6dgAAADBANPSdJl3ty7vYn4b
1Esb2E7a7UD772nhYC3soDO+qyXXSOz+2MGF+BEBm2CC7lQg+ik8vKwlBQT7mu8SC3jnA6
YgsbA2Ng+0gNW+mCzOCE2npJdY7oTjHZAB6TxqV6d/F5NwXLv8e5nuRYvMCVMPwEiS/1Ds
K3ldJ11XOhAJyjF1O2ZEHi+KEcSt7xLy29i58gxbziWK5I+oNoiPIzXRDFiOUzdTqxgaqp
TaYOEFNWKj7mqhCQv1XaeMww14ET9PlwAAAMEAymrHw+CE/8GKsXMlfMN4kpqigcIhZ3Ew
v2rChnQZge1WFFfZ5WLunt/1lNdbUkajufP7jnUwfskcG9+58Z/jLyZvwixL0M93ayBUXS
dNgP0QGpuHJPb0eCuPU8sPTI7wazzutFboZM4lH6u+exHxJDc+iSK+CY3GBghKUnM43QxL
xkZH3qnoLqCwvROtFTP9hJmLaBBqP9dXNoKyZ5S4x57HTjgcu0GJ02FyecB12I/XnUHuLH
42fAYf1HwlYIf1AAAAF3VidW50dUBpcC0xNzItMzEtNDEtMjI2AQID
-----END OPENSSH PRIVATE KEY-----"
          script: sh deploy.sh